#ifndef H_PIN_MEGA
#define H_PIN_MEGA

#include "Arduino.h"

/////////////////////// A //////////////////////
#define DPIN_22 PA0
#define DPIN_23 PA1
#define DPIN_24 PA2
#define DPIN_25 PA3
#define DPIN_26 PA4
#define DPIN_27 PA5
#define DPIN_28 PA6
#define DPIN_29 PA7
/////////////////////// B //////////////////////
#define DPIN_53 PB0
#define DPIN_52 PB1
#define DPIN_51 PB2
#define DPIN_50 PB3
#define DPIN_10 PB4
#define DPIN_11 PB5
#define DPIN_12 PB6
#define DPIN_13 PB7
/////////////////////// C ///////////////////////
#define DPIN_37 PC0
#define DPIN_36 PC1
#define DPIN_35 PC2
#define DPIN_34 PC3
#define DPIN_33 PC4
#define DPIN_32 PC5
#define DPIN_31 PC6
#define DPIN_30 PC7
/////////////////////// D //////////////////////
#define DPIN_21 PD0
#define DPIN_20 PD1
#define DPIN_19 PD2
#define DPIN_18 PD3
#define DPIN_38 PD7
/////////////////////// E /////////////////////////
#define DPIN_0 PE0
#define DPIN_1 PE1
#define DPIN_5 PE3
#define DPIN_2 PE4
#define DPIN_3 PE5
/////////////////////// F //////////////////////
#define APIN_1 PF0
#define APIN_2 PF1
#define APIN_3 PF2
#define APIN_4 PF3
#define APIN_5 PF4
#define APIN_6 PF5
#define APIN_7 PF6
/////////////////////// G ////////////////////////
#define DPIN_41 PG0
#define DPIN_40 PG1
#define DPIN_39 PG2
#define DPIN_4 PG5
/////////////////////// H ////////////////////////
#define DPIN_17 PH0
#define DPIN_16 PH1
#define DPIN_6 PH3
#define DPIN_7 PH4
#define DPIN_8 PH5
#define DPIN_9 PH6
/////////////////////// J ///////////////////////
#define DPIN_15 PJ0
#define DPIN_14 PJ1
/////////////////////// K //////////////////////
#define APIN_8 PK0
#define APIN_9 PK1
#define APIN_10 PK2
#define APIN_11 PK3
#define APIN_12 PK4
#define APIN_13 PK5
#define APIN_14 PK6
#define APIN_15 PK7
/////////////////////// L //////////////////////
#define DPIN_49 PL0
#define DPIN_48 PL1
#define DPIN_47 PL2
#define DPIN_46 PL3
#define DPIN_45 PL4
#define DPIN_44 PL5
#define DPIN_43 PL6
#define DPIN_42 PL7

#endif